architecture:
  Xandrw\ArchitectureEnforcer\Commands:
    - Xandrw\ArchitectureEnforcer\Domain
    - Xandrw\ArchitectureEnforcer\Infrastructure
  Xandrw\ArchitectureEnforcer\Infrastructure:
    - Xandrw\ArchitectureEnforcer\Domain
  Xandrw\ArchitectureEnforcer\Domain:
    - Xandrw\ArchitectureEnforcer\Domain # self-reference marks the layer as strict
    - Symfony # the Symfony namespace may be used

ignore:
  - tests
  - vendor
