architecture:
  Xandrw\ArchitectureEnforcer\Commands:
    - Xandrw\ArchitectureEnforcer\Commands
    - Xandrw\ArchitectureEnforcer\Domain
  Xandrw\ArchitectureEnforcer\Domain: []

ignore:
  - tests
  - vendor