#!/usr/bin/env php
<?php

$autoloadPossiblePaths = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php',
];

foreach ($autoloadPossiblePaths as $autoloadPossiblePath) {
    if (file_exists($autoloadPossiblePath)) {
        define('ENFORCER_COMPOSER_INSTALL', $autoloadPossiblePath);
        break;
    }
}

unset($autoloadPossiblePaths);
unset($autoloadPossiblePath);

require ENFORCER_COMPOSER_INSTALL;

use Symfony\Component\Console\Application;
use Xandrw\ArchitectureEnforcer\Commands\ValidateArchitectureCommand;

$application = new Application('xandrw/architecture-enforcer');
$application->add(new ValidateArchitectureCommand());
$application->run();