#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Xandrw\ArchitectureEnforcer\ValidateArchitectureCommand;

$application = new Application('architecture-enforcer');
$application->add(new ValidateArchitectureCommand());
$application->run();