name: Run tests on version tag

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - uses: php-actions/composer@v6

      - uses: php-actions/phpunit@v3
        with:
          args: --coverage-text --test-suffix=Test.php tests