name: Run tests on version tag

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6

      - name: Run Enforcer
        run: ./enforcer validate src config.yaml

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          test_suffix: Test.php
          php_version: '8.1'
          version: '9.6'