name: Run tests on version tag

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6

      - name:
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          args: --coverage-text --test-suffix=Test.php tests
          php_version: '8.1'